#+TITLE:       Curso básico para alumnos sobre software libre y programación
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE: "header.org"
#+OPTIONS: toc:nil timestamp:nil
#+DATE:        2011-11-10

Miércoles 9 de noviembre de 2011

Conectar Igualdad invita a todos los alumnos de tercer a quinto año de
escuelas secundarias de gestión pública a participar del curso básico
gratuito sobre software libre y programación (GNU/Linux).

La capacitación será realizada en tres jornadas de 9 a 12: 30 horas, los
días jueves 24 y martes 29 de noviembre y el jueves 1º de diciembre en
el Microcine de Conectar Igualdad (Córdoba 1801).

Durante los encuentros, coordinados por Javier Castrillo -experto en el
área de Software Libre aplicado a la educación-, los asistentes podrán
introducirse al mundo de la programación con software libre y el
desarrollo de aplicaciones. El objetivo es comprender que utilizar
computadoras y modificar lo que hacen es más sencillo de lo que parece,
sólo se tienen que conocer las herramientas y conceptos básicos para
empezar.

En esta introducción al diseño de programas se utilizarán herramientas
como el sistema operativo Ubuntu, el intérprete de comandos Bash y el
lenguaje Python.

No se necesita experiencia previa en el manejo de computadoras y se
entregará todo el material de estudio, apuntes y herramientas de
software.

*El curso es libre y gratuito con cupo limitado por lo que los
inscriptos serán confirmados mediante un e-mail.*

Para anotarte, completar formulario en:

- http://www.conectarigualdad.gob.ar/sin-categoria/software-libre-y-programacion/


