#+TITLE:       gcoop tiene Códigos Cooperativos
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2012-08-30

Ya no solo desarrollamos Software Libre, en este caso presentamos un Corto
Documental que produjimos en el que buscamos contar de manera amena lo que
hacemos y las implicancias sociales del cooperativismo y el Software Libre.

La idea de hacer un Corto surgió a partir de la Convocatoria de la
*Confederación Cooperativa de la Argentina*
([[http://cooperar.coop/][COOPERAR]]) que invitó a presentar proyectos
de video que cuenten diversas experiencias cooperativas para el
[[http://www.cac2012.coop][Congreso Argentino de las Cooperativas]]

En este marco convocamos al Director *Daniel Henriquez* y su
*Cooperativa La olla* para trabajar el proyecto (dirección, guión,
filmación, edición) como asi también a
[[http://www.licuadorastudio.com/][Licuadora Studio]] para las
animaciones gráficas (con software libre). La música original la realizó
especialmente para el corto (y la liberó) el grupo amigo
[[http://www.camanchaca.com.ar/][Camanchaca]]

Este sábado a las 15.30 horas los invitamos al
[[http://www.pueblo.coop/][Pueblo Cooperativo]] que se encuentra en
[[http://tecnopolis.ar/][Tecnopolis]] para disfrutar entre amigos de una
**avant - premier** de "Códigos Cooperativos". Acorde a nuestra
filosofía el corto tiene licencia Creative Commons por lo que pronto lo
pondremos a circular por el mundo. Los esperamos.

[[http://www.youtube.com/watch?v=sMI1HA9mOmc&feature=youtu.be][img/codigos-cooperativos.jpg]]

