#+TITLE:     Percona Live 17 =EZE -> DFW -> SJO=
#+AUTHOR:    Osiris Alejandro Gómez
#+EMAIL:     osiux@osiux.com
#+LANGUAGE:  es
#+LINK_HOME: index.html
#+INCLUDE:   header.org
#+DATE:      2017-04-23

#+INCLUDE: "2017-04-23-percona-live-17-header.org"

** Viajando desde EZE con escala en DFW para llegar a SJO

   Fue mi primera vez en viajar a /EEUU/ asi que toda una experiencia
   nueva, empezando por la distancia a recorrer 8523Km en línea recta
   entre /Ezeiza/ y /Dallas/ donde fue mi primer escala y desde ahí
   hasta el aeropuerto de /San Jose/ otros 2334Km aprox, que traducido
   en horas, fueron 10hs el vuelo internacional y 3hs el vuelo de
   cabotaje.

   No deja de sorprenderme cada vez que subo a un avión como logran
   despegar y estar en el aire menos de 60 segundos que por lo general
   son 50 segundos de tomar carrera y los últimos 10 segundos ya
   empezó a volar.

   El avión llegó temprano a /Dallas/ (04:40 AM Hora del pacífico) y
   tuvimos que esperar porque todavía Migración no había abierto,
   luego el primer control, una máquina que escanea el pasaporte y te
   hace unas preguntas para finalmente imprimir un papel y con éste ir
   a charlar con el oficial de migración no sin antes pasar por un
   scanner 3d sin zapatos, cinturón, ni nada de lo que llevás encima,
   todo eso pasa por otro scanner. Una vez que el oficial te sella el
   pasaporte, pasas al espacio en tránsito y en este aeropuerto en
   participar hay que tomarse un tren para ir de una terminal a otra,
   son 4 de la A a la D y cada terminal es enorme.

** AirBnB

   El alojamiento que recomendaba el evento era en el Hyatt Regency, el
   cual esta conectado al centro de convenciones de Santa Clara, pero
   claro por lo que salía una sola noche, conseguí por el mismo precio
   las 7 noches gracias a AirBnB a unas pocas cuadras, cruzando el
   Levi's Stadium
