#+TITLE:     Percona Live 17 =san francisco=
#+AUTHOR:    Osiris Alejandro Gómez
#+EMAIL:     osiux@osiux.com
#+LANGUAGE:  es
#+LINK_HOME: index.html
#+INCLUDE:   header.org
#+DATE:      2017-04-28

#+INCLUDE: "2017-04-23-percona-live-17-header.org"

** San Francisco

   Aprovechando que no estaba muy lejos, emprendí la excursión a San
   Francisco, para esto primero tomé el Ligth Rail Train hasta Down Town
   Mountan View y ahí combiné con el CALTrain hasta San Francisco, en la
   combinación me topé con una Señora Argentina que al escuchar su
   acento porteño la encaré para pedirle sugerencias sobre San Francisco
   y para hacerla corta me contó la historia de su vida, vino a Santa
   Clara con la crisis del 2001 y en resumen no fue fácil adaptarse y me
   dijo que no hay que tomarse con liviandad lo de vivir en otro país.
   La buena fue luego de compartir un viaje de intercambio de costumbres
   argentinas y gringas nos dimos un beso y un fuerte abrazo, parece
   mentira pero no lo hice con nadie más en toda mi estadía, no es común
   invadir el espacio personal por estos lados.

   Desde la terminal de CALTrain en la 4th y Kings caminé como para
   recorrer un poco el lugar y terminé en el AT&T Park al lado del
   stadio de beisbol de los Gigantes de San Francisco, asi llegué a ver
   el esplendor de la bahía de San Francisco, seguí paseando y llegué al
   Museo de Arte Moderno de San Francico y avancé al parque Yerba Buena,
   luego fui a Market y la 5th y subí a un tranvía, el cual presentó el
   inconveniente de que era solo efectivo y pago exacto, asi que en
   lugar de abonar 2.5 USD me costó 3.00 USD (no termino de entender
   porqué una máquina que recibe monedas no da cambio?)

   Con el tranvía llegué hasta Pier 39 donde pasando los puestos de
   comida muy para turistas, encontré la atracción del lugar, un par
   de decenas de Leones Marinos intentando tomar una siesta sobre un
   muelle y disputando los lugares haciendo mucho ruido.

   Desde este lugar se vía con claridad Alcatraz y se vislumbraba el
   Golden Gate, asi que miré en el mapa y parecía estar cerca, había un
   sendero para ciclistas y no me convenció el alquiler de bicicletas
   (36 USD las 24hs o 8 USD por hora, más depósito) asi que dije, si veo
   el puente, tan lejos no está y emprendí la marcha. Hacía mucho tiempo
   que no caminaba tanto! :P a medida que me acercaba, el puente parecía
   estar más cerca y al mismo tiempo seguía estando lejos, dejé de
   cruzarme con peatones y ya estaba en la zona de ascenso de la
   autopista hacia el puente y no estaba claro que hubiera manera de
   subir para un peatón, asi que me propuse llegar hasta la base por lo
   menos, la buena es que pasee por una pequeña playa y luego un muelle
   para finalmente encontrar un empinado sendero hacia el puente.

   Ya caminando por el puente, me di cuenta de dos cosas:

   1. El puente es muy alto
   2. Tengo vértigo :P

   ... Pero bueno, parecía bastante sólido, es increíble que sea un
   puente colgante de 1890.

   Desde arriba se podía ver el océano pacífico o el comienzo al menos
   ya que había bastante niebla. El ruido de los autos pasar era un
   tanto ruidoso, pero bueno ahí estaba en la mitad del puente y
   obtuve buenas fotos, aunque cansado de tanto caminar obtuve una
   gratificación, el tema era seguir caminado hasta el otro lado o
   volver? Pregunté si había algún Bus del otro lado y una gringa me
   dijo que no tenía idea, que podía pedir un Uber XD así que volví
   para el lado sur y en el camino paré a un oficial de policía en
   bicicleta y me indicó como llegar a la parada del Bus, así que
   caminé hasta ahí, tuve que pasar por debajo de un túnel y encontré
   lo mismo de siempre en las paradas de transporte público, asiáticos
   que al parecer junto a los latinos e indios son medios los únicos
   que usan el transporte público. En fin había un cartel que indicaba
   que líneas pasaban y dónde me dejaban, el tema es que estaba claro
   que debía abonar 5 USD exactos y en efectivo, por suerte tenía
   justo uno y luego de una espera, pude subir y llegar hasta mocase,
   como ya era de noche, ni bien bajé del Bus corrí hasta el CalTrain
   porque suponía que ya era tarde para el tren, fue una decisión
   doblemente acertada, primero porque gracias a la corrida llegué
   justo al tren de las 20:30 y en Montan View llegué a las 21:44, asi
   que baje corriendo para combinar con el Ligth Trail y mientras
   estaba por salir yo cruzaba los dedos mientras la expendedora me
   decía *autorizando tarjeta de crédito* y dio error (la puse al
   revés, capa 8), ni bien salió el ticket corrí y lo agarré justo,
   entré y tome una de las guías con horarios, miré hasta que hora
   había servicio y descubrí que era el último del día...(en esos
   momentos uno se vuelve creyente o al menos un suertudo)

   Me quedaron mil cosas por conocer en San Francisco, claramente
   tiene todo para disfrutar, paisajes, arte y mucha vida nocturna,
   aunque me sorprendió muchísimo la cantidad de homeless que hay,
   incluso en mi corrida e cruce a una larga fila intentando pasar la
   noche en un albergue.

