#+TITLE:     Percona Live 17 =santa clara=
#+AUTHOR:    Osiris Alejandro Gómez
#+EMAIL:     osiux@osiux.com
#+LANGUAGE:  es
#+LINK_HOME: index.html
#+INCLUDE:   header.org
#+DATE:      2017-04-29

#+INCLUDE: "2017-04-23-percona-live-17-header.org"

** Santa Clara

   Último día y muchas posibilidades, asi que teniendo en cuenta el
   agotador día anterior, opte por un recorrido mas cercano, comencé a
   caminar con dirección al Intel Museum, si bien podía hacer alguna
   combinación entre metro y bus, el tiempo era el mismo que ir a pata
   y de esta manera podría conocer un poco mas la
   ciudad. Definitivamente Santa Clara no es una ciudad para caminar,
   si bien las veredas están limpias y parquizadas, es casi un
   desierto, no te cruzas a nadie por el camino, son todas avenidas,
   autopistas y no existe el concepto de kiosco, asi que no donde
   comprar algo en el camino, aunque con un poco de suerte cada 30
   cuadras (para nada uniformes) te topas con una especie de
   mini-super.

*** Intel Museum

    El museo lo recorrés en 10 minutos y no creo que resulte
    interesante si no sos un ñoño que aprecie ver un ALTAIR, no hay
    mucho mas para decir.

*** Milpitas

    Volvi a patear hasta el Ligth Trail para bajar en Milpitas y
    volver a patear hasta llegar a un BestBuy, Ross y Wallmart

*** Alviso Marina County Park

    Nuevamente volver a patear hasta el Ligth Trail para bajar en Lock
    Mill y tomar el Guadalupe Creek Trail, un sendero para ciclistas
    que según vi en OpenStreetMap me llevava hasta el Alviso Marina
    County Park, larguisima la caminata, aunque interesante el paisaje
    a medida que avanzaba se volvia mas agreste hasta llegar al borde
    la Bahía y descubrir una reversa ecológica con amplia variedad de
    aves y lo mejor, lo que quedó de la extrción de sales, eso le da
    esos colores extraños a las fotos satelitales, un bonito atardecer
    y otra vez a patear, no hay otra opción si no tenés bici o auto.
