#+TITLE:       la escala lo cambia todo
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE: "header.org"
#+OPTIONS: toc:nil timestamp:nil
#+DATE:        2012-05-23

Llevo más de seis años participando del proyecto *BuenosAiresLibre*
también conocido como BAL [fn:BAL] y hemos realizado todo tipo de
acciones para hacer crecer la red, desde la mera difusión de las
ventajas de ser parte de una red libre, autogestionada por sus propios
usuarios hasta la capacitación técnica mediante talleres de construcción
de antenas como también sobre configuración de distintos equipos, sin
olvidar las innumerables presentaciones, charlas y todo el conocimiento
colectivo acumulado en el wiki [fn:wiki] del proyecto disponible para
cualquiera que tenga ganas de leerlo y modificarlo.

*¿Porqué la red no está tal y como la queremos?. ¿Porqué no hay tantos
nodos y enlaces?*. Seguramente hay muchísimas causas posibles!

No pretendo tirar todo el trabajo realizado por cientos de personas a lo
largo de más de 10 años, todo lo contrario, me parece que debemos
focalizar nuestro esfuerzo porque *¡la escala lo cambia todo!* En
cierto sentido creo que todo lo que se hizo en el proyecto estuvo bien,
algunas decisiones tal vez fueron más efectivas que otras pero visto en
general todo sirvió para llegar a donde estamos hoy y no está mal
mantener viva la idea de que *una red abierta y comunitaria es posible de
realizar*, sólo nos falta reducir la escala para ser más efectivos.

Así que el lema *"si en tu barrio no hay un nodo es porque vos no lo
armaste"* lo cambiaría por *"si en tu barrio no hay una red libre, es
momento de crearla y unirla a otras redes libres"*.

Habiendo participado de la creación de nuevas y pequeñas redes libres,
me consta que un grupo reducido de integrantes es más dinámico, con un
sentido de pertenencia muy alto por tratarse de vecinos, que tienen
una necesidad puntual a resolver y es la falta de una red digital de
datos que permita comunicarse en el barrio/pueblo/ciudad y tener
salida al mundo, pero con las características específicas de ese
lugar. Una muestra de esto son las redes *QuintanaLibre* [fn:QL]
y *DeltaLibre* [fn:DL] que comparten el mismo diseño [fn:redlibre] por
ser laboratorios del proyecto *ArraigoDigital* [fn:arraigo], ambas
surgieron por algo muy concreto, cada una tiene un pionero de BAL que
necesita una buena conexión al mundo para realizar su trabajo y esto
no era posible sólo con los ISP y WISP locales, para ello fue
necesario levantar varios enlaces los cuales son aprovechados para
todos los beneficios que brindan las redes libres, instalando muchos
servicios en la red local que están siempre disponibles, aún cuando no
hay conexión al mundo.

Técnicamente siempre hay una manera de conectar una red con otra red,
aunque usen protocolos de enrutamiento muy distintos, hoy
*LibreVPN* [fn:LVPN] es un proyecto que está uniendo varias redes
libres de Argentina y ya son parte algunas redes de Colombia, es un
experimento y seguramente encontraremos mejores maneras con el tiempo
pero no tengo dudas de que son necesarias redes zonales y me atrevo a
decir que en Buenos Aires sería ideal contar con una red libre por
cada barrio, brindando autonomía barrial para luego interconectar
todas las redes zonales y que sean parte del gran proyecto BAL sin
perder identidad.

Creo que en parte este enfoque reduciría las fricciones y
contratiempos que todos conocemos y que son propios de cualquier
proyecto y gran número de personas involucradas, pretender hacer las
cosas de una sola manera y que todos estemos de acuerdo, cuando
podemos hacerlas de diversas formas y luego interconectarnos y
cooperar.

No olvidemos el primer punto del *Manifiesto de las Redes
Libres* [fn:manifiesto] *garantizar la descentralización* y el punto
seis *promover la creación de otras redes libres, su interconexión e
interoperabilidad*.

*BAL* siempre ha fomentado la creación y unión de nuevas redes libres
dentro y fuera del país, es hora de empezar por casa!

[fn:BAL]        http://www.buenosaireslibre.org
[fn:wiki]       http://wiki.buenosaireslibre.org
[fn:manifiesto] http://redeslibres.org/es/manifiesto-de-las-redes-libres
[fn:QL]         http://wiki.arraigodigital.org.ar/RedLibre/QuintanaCamp
[fn:DL]         http://wiki.arraigodigital.org.ar/RedLibre/DeltaCamp
[fn:redlibre]   http://wiki.arraigodigital.org.ar/RedLibre/Diseño
[fn:arraigo]    http://wiki.arraigodigital.org.ar
[fn:LVPN]       http://librevpn.org.ar
